version: 2
updates:
- package-ecosystem: pip
  directory: "/notebooks"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/binder"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
