version: 2
updates:
- package-ecosystem: pip
  directory: "/notebook-tests"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/pydemolib"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
