#!/bin/bash

python -c "import tests;tests.fetch_hadoop()"

python -c "import tests;tests.fetch_hive_with_iceberg_jars()"

HADOOP_VERSION=`python -c "import tests;print(tests._HADOOP_VERSION)"`

HIVE_VERSION=`python -c "import tests;print(tests._HIVE_VERSION)"`

export HADOOP_HOME=$PWD/hadoop-$HADOOP_VERSION

#Start Hive
chmod +x $PWD/../binder/start.hive
nohup $PWD/../binder/start.hive $PWD $PWD/../binder/resources $HIVE_VERSION