#!/bin/bash

python -c "import utils;utils.fetch_hadoop()"

python -c "import utils;utils.fetch_hive_with_iceberg_jars()"

HADOOP_VERSION=`python -c "import utils;print(utils._HADOOP_VERSION)"`

HIVE_VERSION=`python -c "import utils;print(utils._HIVE_VERSION)"`

export HADOOP_HOME=$PWD/hadoop-$HADOOP_VERSION

#Start Hive
chmod +x $PWD/../docker/binder/start.hive
nohup $PWD/../docker/binder/start.hive $PWD $PWD/../docker/binder/resources $HIVE_VERSION