#
# Copyright (C) 2020 Dremio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# Special configuration to run a Nessie Demo against Nessie and/or Iceberg built locally from source.
#
# Requires four environment variables:
#
# NESSIE_DEMO_IN_DEV_NESSIE_RUNNER : the path of the Nessie runner, usually the Nessie Quarkus Runner native image
# NESSIE_DEMO_IN_DEV_NESSIE_VERSION : the Nessie version, usually a SNAPSHOT version
# NESSIE_DEMO_IN_DEV_PYNESSIE_PATH : the path to the pynessie Wheel in the nessie/python/dist directory, built with e.g. `python -m build`"
#
# Instructions:
# 1. Setup projectnessie/nessie
# 1.1. Build Nessie w/ native image:
#      `./mvnw clean install -DskipTests -Pnative`
# 1.2. Get Nessie version
#      `./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout`
# 1.3. Build pynessie
#      Run `python -m build` in a virtualenv in the Nessie source tree within the `python/` directory
# 2. Set environment variables:
#    NESSIE_DEMO_IN_DEV_NESSIE_RUNNER to the full path within the Nessie source tree in servers/quarkus/target/...
#    NESSIE_DEMO_IN_DEV_NESSIE_VERSION to the version from step 1.2
#    NESSIE_DEMO_IN_DEV_PYNESSIE_PATH to the `.whl` file within the Nessie source tree in `python/dist/`

### THIS IS A CONFIG INTENDED FOR NESSIE DEVELOPERS! ###

versions:
  nessie: !env NESSIE_DEMO_IN_DEV_NESSIE_VERSION
  iceberg: 0.11.1

python_dependencies:
  - findspark==1.4.2
  - pyspark==3.0.2
  - pandas==1.2.4
  - pyarrow==4.0.0

python_dependencies_reinstall:
  - !env NESSIE_DEMO_IN_DEV_PYNESSIE_PATH

nessie_runner: !env NESSIE_DEMO_IN_DEV_NESSIE_RUNNER
