#!/bin/bash
#
# Copyright (C) 2020 Dremio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

PYTHON_VERSION=`python --version|awk '{print $2}'`

python --version
source /srv/conda/etc/profile.d/conda.sh
conda create -n flink-demo pandas ipykernel requests python=="$PYTHON_VERSION"
conda activate flink-demo
pip install -r "binder/requirements_flink.txt"
python -m ipykernel install --name "flink-demo" --user
python -c "import utils;utils._copy_all_hadoop_jars_to_pyflink()"
conda deactivate

python -c "import utils;utils.fetch_nessie()"

python -c "import utils;utils.fetch_spark()"

python -c "import utils;utils.fetch_iceberg_flink()"

python -c "import utils;utils.fetch_hive_with_iceberg_jars()"
