#!/bin/bash

FLINK_VERSION=1.12.1

NESSIE_VERSION=`python -c "import pynessie;print(pynessie.__version__)"`
PYTHON_VERSION=`python --version|awk '{print $2}'`

python --version
source /srv/conda/etc/profile.d/conda.sh
conda create -n flink-demo pandas ipykernel requests python=="$PYTHON_VERSION"
conda activate flink-demo
pip install apache-flink=="$FLINK_VERSION" pynessie=="$NESSIE_VERSION"
python -m ipykernel install --name "flink-demo" --user
python -c "import notebooks.tests;notebooks.tests._copy_all_hadoop_jars_to_pyflink()"
conda deactivate

python -c "import notebooks.tests;notebooks.tests.fetch_nessie()"

python -c "import notebooks.tests;notebooks.tests.fetch_spark()"

python -c "import notebooks.tests;notebooks.tests.fetch_iceberg_flink()"
