#!/bin/bash

nohup ./nessie-quarkus-runner &

SPARK_VERSION=`python -c "import notebooks.tests;print(notebooks.tests._SPARK_VERSION)"`
HADOOP_VERSION=`python -c "import notebooks.tests;print(notebooks.tests._HADOOP_VERSION)"`

export SPARK_HOME=$PWD/spark-$SPARK_VERSION-bin-hadoop3.2
export HADOOP_HOME=$PWD/hadoop-$HADOOP_VERSION
exec "$@"
